//! NatSQL → llguidance Lark grammar generator.
//!
//! Stage 2 (skeleton generator) decodes under a constrained grammar so
//! the model cannot emit identifiers that don't exist in the live
//! schema. The grammar is built **per-query** from Stage 1's top-k
//! schema items — typically <20 entities and <100 fields — so the CFG
//! stays tiny regardless of the underlying database size. This is the
//! structural advantage of the cascade over a single-shot LLM: the
//! grammar bounds the search space *exactly* to what's relevant.
//!
//! Grammar surface (Lark dialect, llguidance-compatible):
//!
//! ```text
//! start:        select_stmt
//! select_stmt:  "SELECT" select_list "FROM" entity where_clause? group_clause? order_clause? limit_clause?
//! select_list:  "*" | aggregate | field_list
//! field_list:   field ("," field)*
//! aggregate:    AGG "(" (field | "*") ")"
//! AGG:          "COUNT" | "SUM" | "AVG" | "MIN" | "MAX"
//! where_clause: "WHERE" condition
//! condition:    field CMP value
//! CMP:          "=" | "!=" | "<" | ">" | "<=" | ">="
//! ...
//! entity:       "users" | "orders" | "tenants" | ...      (per-query)
//! field:        "users.id" | "users.email" | ...           (per-query)
//! value:        "@val1" | "@val2" | ... | NUMBER | STRING
//! ```
//!
//! `entity` and `field` are the only productions that vary per query —
//! everything else is static and round-trips cleanly through the
//! NatSQL parser in `semsql-natsql`.
//!
//! The generator escapes identifiers that contain Lark metacharacters
//! (rare — canonical names are `[A-Za-z_][A-Za-z0-9_]*` so this is a
//! defensive guard, not a hot path).

use semsql_core::{Result, SemsqlError};
use semsql_natsql::ast::{Condition, Field, NatSql, SelectItem};
use std::collections::BTreeSet;

/// Schema slice handed to the grammar generator. Mirrors what Stage 1
/// emits as its ranked top-k.
#[derive(Clone, Debug, Default)]
pub struct GrammarSchema {
    /// Entity canonical names — drive the `entity` non-terminal.
    pub entities: Vec<String>,
    /// Field canonical names as `entity.field`. Drive the `field`
    /// non-terminal. Each field MUST be qualified — the grammar emits
    /// fully qualified references so the slot filler doesn't have to
    /// re-disambiguate.
    pub fields: Vec<String>,
    /// Distinct value placeholders Stage 2 may emit. Defaults to
    /// `@val1..@val4` if not supplied.
    pub value_slots: Vec<String>,
}

/// Build a Lark grammar string suitable for llguidance.
///
/// Returns the grammar verbatim; the caller is responsible for piping
/// it into `llguidance::TokenParser`. Pure function — no I/O — so the
/// output is stable across runs and trivially testable.
pub fn build_natsql_grammar(schema: &GrammarSchema) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated NatSQL grammar — bound to the active schema slice.\n");
    out.push_str("// Generated by semsql_runtime::grammar::build_natsql_grammar\n\n");

    out.push_str("start: select_stmt\n\n");

    // v0.3: join_clause* allows up to 3 INNER JOINs after the FROM entity.
    out.push_str("select_stmt: \"SELECT\" select_list \"FROM\" entity ");
    out.push_str("join_clause* where_clause? group_clause? having_clause? ");
    out.push_str("order_clause? limit_clause? offset_clause?\n\n");

    // select_list: v0.3 adds arithmetic expression (arith_expr).
    out.push_str("select_list: \"*\" | arith_expr | aggregate | field_list\n");
    out.push_str("field_list: field (\",\" field)*\n");
    out.push_str("aggregate: AGG \"(\" (field | \"*\") \")\"\n");
    out.push_str("AGG: \"COUNT\" | \"SUM\" | \"AVG\" | \"MIN\" | \"MAX\"\n");
    // Arithmetic: field / field or aggregate / field etc.
    out.push_str("arith_expr: (field | aggregate) ARITH_OP (field | aggregate | NUMBER)\n");
    out.push_str("ARITH_OP: \"/\" | \"*\" | \"+\" | \"-\"\n\n");

    // JOIN clause: only INNER JOIN with ON field = field.
    out.push_str("join_clause: \"INNER\" \"JOIN\" entity \"ON\" field \"=\" field\n\n");

    out.push_str("where_clause: \"WHERE\" condition (\"AND\" condition)*\n");
    out.push_str("condition: field CMP value\n");
    out.push_str("CMP: \"=\" | \"!=\" | \"<\" | \">\" | \"<=\" | \">=\"\n\n");

    // HAVING: same structure as WHERE.
    out.push_str("having_clause: \"HAVING\" condition (\"AND\" condition)*\n\n");

    out.push_str("group_clause: \"GROUP\" \"BY\" field (\",\" field)*\n");
    out.push_str("order_clause: \"ORDER\" \"BY\" field (\"DESC\" | \"ASC\")?\n");
    out.push_str("limit_clause: \"LIMIT\" INT\n");
    out.push_str("offset_clause: \"OFFSET\" INT\n\n");

    out.push_str(&entity_production(&schema.entities));
    out.push('\n');
    out.push_str(&field_production(&schema.fields));
    out.push('\n');
    out.push_str(&value_production(schema));
    out.push('\n');

    // Terminals.
    out.push_str("INT: /[0-9]+/\n");
    out.push_str("NUMBER: /-?[0-9]+(\\.[0-9]+)?/\n");
    out.push_str("STRING: /'(?:[^'\\\\]|\\\\.)*'/\n");
    out.push_str("WS: /[ \\t\\n\\r]+/\n");
    out.push_str("%ignore WS\n");
    out
}

fn entity_production(entities: &[String]) -> String {
    if entities.is_empty() {
        // Sentinel — llguidance will reject every input, which is
        // correct: an empty schema can answer no queries.
        return "entity: \"__no_entities__\"\n".into();
    }
    let alts: Vec<String> = sorted_unique(entities)
        .into_iter()
        .map(|e| format!("\"{}\"", lark_escape(&e)))
        .collect();
    format!("entity: {}\n", alts.join(" | "))
}

fn field_production(fields: &[String]) -> String {
    if fields.is_empty() {
        return "field: \"__no_fields__\"\n".into();
    }
    let alts: Vec<String> = sorted_unique(fields)
        .into_iter()
        .map(|f| format!("\"{}\"", lark_escape(&f)))
        .collect();
    format!("field: {}\n", alts.join(" | "))
}

fn value_production(schema: &GrammarSchema) -> String {
    let slots: Vec<String> = if schema.value_slots.is_empty() {
        vec!["@val1".into(), "@val2".into(), "@val3".into(), "@val4".into()]
    } else {
        schema.value_slots.clone()
    };
    let slot_alts: Vec<String> = slots
        .into_iter()
        .map(|s| format!("\"{}\"", lark_escape(&s)))
        .collect();
    format!(
        "value: {} | NUMBER | STRING | \"true\" | \"false\" | \"NULL\"\n",
        slot_alts.join(" | ")
    )
}

fn sorted_unique(xs: &[String]) -> Vec<String> {
    let set: BTreeSet<&str> = xs.iter().map(String::as_str).collect();
    set.into_iter().map(str::to_string).collect()
}

/// Parse `skeleton` as NatSQL and check every entity/field
/// reference appears in the supplied schema slice. This is the
/// runtime backstop for Stage 2 outputs: even when the constrained
/// decode succeeds (the model emitted only grammar-allowed tokens),
/// a buggy grammar generator OR a manually-edited skeleton could
/// still smuggle in an out-of-scope identifier. The validator
/// rejects those before they reach the transpiler / second-pass
/// scope-leak walker.
///
/// Returns the parsed AST on success so callers can plumb it
/// directly into Stage 3 without re-parsing.
///
/// Errors:
///  - `SemsqlError::Validation` if NatSQL parsing fails.
///  - `SemsqlError::Validation` with a precise out-of-scope message
///    if any reference is absent from the schema slice.
pub fn validate_skeleton_against_schema(
    skeleton: &str,
    schema: &GrammarSchema,
) -> Result<NatSql> {
    let parsed = semsql_natsql::parse(skeleton)?;
    let entity_set: BTreeSet<&str> =
        schema.entities.iter().map(String::as_str).collect();
    let field_set: BTreeSet<&str> =
        schema.fields.iter().map(String::as_str).collect();
    for entity in &parsed.entities {
        if !entity_set.contains(entity.as_str()) {
            return Err(SemsqlError::validation(format!(
                "entity `{}` not in active schema slice (allowed: {})",
                entity.as_str(),
                schema.entities.join(", "),
            )));
        }
    }
    check_field_iter(&parsed.select, &entity_set, &field_set, &parsed)?;
    for cond in &parsed.conditions {
        check_condition(cond, &entity_set, &field_set, &parsed)?;
    }
    for f in &parsed.group_by {
        check_field(f, &entity_set, &field_set, &parsed)?;
    }
    if let Some((f, _)) = &parsed.order_by {
        check_field(f, &entity_set, &field_set, &parsed)?;
    }
    for jc in &parsed.joins {
        if !entity_set.contains(jc.entity.as_str()) {
            return Err(SemsqlError::validation(format!(
                "join entity `{}` not in active schema slice",
                jc.entity.as_str(),
            )));
        }
        check_field(&jc.on_left, &entity_set, &field_set, &parsed)?;
        check_field(&jc.on_right, &entity_set, &field_set, &parsed)?;
    }
    for cond in &parsed.having {
        check_condition(cond, &entity_set, &field_set, &parsed)?;
    }
    Ok(parsed)
}

fn check_field_iter(
    items: &[SelectItem],
    entities: &BTreeSet<&str>,
    fields: &BTreeSet<&str>,
    parsed: &NatSql,
) -> Result<()> {
    for item in items {
        match item {
            SelectItem::Star => {}
            SelectItem::Field(f) | SelectItem::Aggregate(_, f) => {
                // `COUNT(*)` lowers to an `Aggregate(Count, Bare("__star__"))`
                // placeholder during parsing; the transpiler renders it
                // back as `*`. Skip schema validation for this synthetic.
                if let Field::Bare(name) = f {
                    if name.as_str() == "__star__" {
                        continue;
                    }
                }
                check_field(f, entities, fields, parsed)?;
            }
            // Raw arithmetic/CAST expressions are passed through verbatim;
            // the second-pass parser validates them against the real schema.
            SelectItem::Expr(_) => {}
        }
    }
    Ok(())
}

fn check_condition(
    cond: &Condition,
    entities: &BTreeSet<&str>,
    fields: &BTreeSet<&str>,
    parsed: &NatSql,
) -> Result<()> {
    let f = match cond {
        Condition::Compare(f, _, _)
        | Condition::In(f, _)
        | Condition::Between(f, _, _)
        | Condition::IsNull(f)
        | Condition::IsNotNull(f)
        | Condition::Like(f, _) => f,
    };
    check_field(f, entities, fields, parsed)
}

fn check_field(
    f: &Field,
    entities: &BTreeSet<&str>,
    fields: &BTreeSet<&str>,
    parsed: &NatSql,
) -> Result<()> {
    match f {
        Field::Qualified(fn_) => {
            let dotted = format!("{}", fn_);
            if !fields.contains(dotted.as_str()) {
                return Err(SemsqlError::validation(format!(
                    "field `{dotted}` not in active schema slice"
                )));
            }
            if !entities.contains(fn_.entity.as_str()) {
                return Err(SemsqlError::validation(format!(
                    "field `{dotted}` references entity `{}` outside active schema slice",
                    fn_.entity.as_str(),
                )));
            }
        }
        Field::Bare(name) => {
            // A bare field is unambiguous only when the parsed query
            // pins exactly one entity. We verify by trying every
            // schema entity as a prefix; at least one match must
            // exist AND the inferred entity must be in the parsed
            // query's entity set.
            let candidates: Vec<&str> = parsed
                .entities
                .iter()
                .filter(|e| {
                    let dotted = format!("{}.{}", e.as_str(), name.as_str());
                    fields.contains(dotted.as_str())
                })
                .map(|e| e.as_str())
                .collect();
            if candidates.is_empty() {
                return Err(SemsqlError::validation(format!(
                    "bare field `{}` matches no field in active schema slice",
                    name.as_str()
                )));
            }
            if candidates.len() > 1 {
                return Err(SemsqlError::validation(format!(
                    "bare field `{}` is ambiguous across entities {}",
                    name.as_str(),
                    candidates.join(", ")
                )));
            }
        }
    }
    Ok(())
}

/// Lark string-literal escape — backslash and double-quote.
fn lark_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            _ => out.push(ch),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn produces_alphabetised_deduplicated_alternatives() {
        let schema = GrammarSchema {
            entities: vec!["users".into(), "orders".into(), "users".into()],
            fields: vec!["users.email".into(), "orders.id".into()],
            value_slots: vec![],
        };
        let g = build_natsql_grammar(&schema);
        // Entities alphabetised + deduplicated.
        let entity_line = g.lines().find(|l| l.starts_with("entity:")).unwrap();
        assert!(entity_line.contains("\"orders\""));
        assert!(entity_line.contains("\"users\""));
        assert_eq!(entity_line.matches("\"users\"").count(), 1, "deduplicated");
        // `orders` precedes `users` lexicographically.
        let o = entity_line.find("\"orders\"").unwrap();
        let u = entity_line.find("\"users\"").unwrap();
        assert!(o < u, "alphabetised");
    }

    #[test]
    fn empty_schema_emits_sentinel_unmatchable_productions() {
        let g = build_natsql_grammar(&GrammarSchema::default());
        assert!(g.contains("__no_entities__"));
        assert!(g.contains("__no_fields__"));
    }

    #[test]
    fn includes_default_slot_set_when_caller_does_not_specify() {
        let g = build_natsql_grammar(&GrammarSchema {
            entities: vec!["x".into()],
            fields: vec!["x.y".into()],
            value_slots: vec![],
        });
        for slot in ["@val1", "@val2", "@val3", "@val4"] {
            assert!(g.contains(slot), "expected {slot} in grammar");
        }
    }

    #[test]
    fn caller_supplied_slots_override_defaults() {
        let g = build_natsql_grammar(&GrammarSchema {
            entities: vec!["x".into()],
            fields: vec!["x.y".into()],
            value_slots: vec!["@param".into(), "@nl1".into()],
        });
        assert!(g.contains("@param"));
        assert!(g.contains("@nl1"));
        assert!(!g.contains("@val1"), "default slots replaced when caller supplies");
    }

    #[test]
    fn escapes_lark_metacharacters_in_identifiers() {
        // `is_safe_canonical` makes this defensive — but we still want
        // the escaper to work on hostile input that bypassed the gate.
        let schema = GrammarSchema {
            entities: vec!["weird\"name".into()],
            fields: vec!["weird\\name.col".into()],
            value_slots: vec![],
        };
        let g = build_natsql_grammar(&schema);
        assert!(g.contains("\"weird\\\"name\""));
        assert!(g.contains("\"weird\\\\name.col\""));
    }

    #[test]
    fn validate_accepts_in_scope_skeleton() {
        let schema = GrammarSchema {
            entities: vec!["users".into()],
            fields: vec!["users.email".into(), "users.id".into()],
            value_slots: vec![],
        };
        let parsed = validate_skeleton_against_schema(
            "SELECT users.email FROM users WHERE users.id = 1",
            &schema,
        );
        assert!(parsed.is_ok(), "{:?}", parsed.err());
    }

    #[test]
    fn validate_rejects_out_of_scope_entity() {
        let schema = GrammarSchema {
            entities: vec!["users".into()],
            fields: vec!["users.id".into()],
            value_slots: vec![],
        };
        let err = validate_skeleton_against_schema(
            "SELECT orders.id FROM orders",
            &schema,
        )
        .unwrap_err()
        .to_string();
        assert!(err.contains("orders"), "{err}");
        assert!(err.contains("schema slice"), "{err}");
    }

    #[test]
    fn validate_rejects_out_of_scope_field() {
        let schema = GrammarSchema {
            entities: vec!["users".into()],
            fields: vec!["users.id".into()],
            value_slots: vec![],
        };
        let err = validate_skeleton_against_schema(
            "SELECT users.secret FROM users",
            &schema,
        )
        .unwrap_err()
        .to_string();
        assert!(err.contains("users.secret"), "{err}");
    }

    #[test]
    fn validate_resolves_bare_field_when_unambiguous() {
        let schema = GrammarSchema {
            entities: vec!["users".into()],
            fields: vec!["users.email".into(), "users.id".into()],
            value_slots: vec![],
        };
        let parsed = validate_skeleton_against_schema(
            "SELECT email FROM users",
            &schema,
        );
        assert!(parsed.is_ok(), "{:?}", parsed.err());
    }

    #[test]
    fn validate_rejects_bare_field_with_no_match() {
        let schema = GrammarSchema {
            entities: vec!["users".into()],
            fields: vec!["users.id".into()],
            value_slots: vec![],
        };
        let err = validate_skeleton_against_schema(
            "SELECT phone FROM users",
            &schema,
        )
        .unwrap_err()
        .to_string();
        assert!(err.contains("phone"), "{err}");
    }

    #[test]
    fn validate_accepts_inner_join_in_scope() {
        let schema = GrammarSchema {
            entities: vec!["users".into(), "orders".into()],
            fields: vec!["users.id".into(), "orders.user_id".into()],
            value_slots: vec![],
        };
        let r = validate_skeleton_against_schema(
            "SELECT * FROM users INNER JOIN orders ON orders.user_id = users.id",
            &schema,
        );
        assert!(r.is_ok(), "{:?}", r.err());
    }

    #[test]
    fn validate_rejects_join_entity_out_of_scope() {
        let schema = GrammarSchema {
            entities: vec!["users".into()],
            fields: vec!["users.id".into()],
            value_slots: vec![],
        };
        let err = validate_skeleton_against_schema(
            "SELECT * FROM users INNER JOIN orders ON orders.user_id = users.id",
            &schema,
        )
        .unwrap_err()
        .to_string();
        assert!(err.contains("orders"), "{err}");
    }

    #[test]
    fn validate_accepts_having_in_scope() {
        let schema = GrammarSchema {
            entities: vec!["users".into()],
            fields: vec!["users.status_code".into()],
            value_slots: vec![],
        };
        let r = validate_skeleton_against_schema(
            "SELECT users.status_code FROM users GROUP BY users.status_code HAVING users.status_code > 2",
            &schema,
        );
        assert!(r.is_ok(), "{:?}", r.err());
    }

    #[test]
    fn grammar_is_pure_and_deterministic() {
        let schema = GrammarSchema {
            entities: vec!["users".into(), "orders".into()],
            fields: vec!["users.id".into(), "users.email".into()],
            value_slots: vec!["@v".into()],
        };
        let a = build_natsql_grammar(&schema);
        let b = build_natsql_grammar(&schema);
        assert_eq!(a, b, "byte-identical output across calls");
    }
}
