//! Two-parser-must-agree differential test.
//!
//! Reads `tests/fixtures/two_parser_corpus.jsonl` (regenerated by the
//! Python rewriter test suite) and verifies that every Python-produced SQL
//! string is accepted by the Rust second-pass walker with the same scope
//! invariants — and that hand-written negative-control SQL is rejected.
//!
//! If this test fails, sqlglot and sqlparser-rs disagree on the contract
//! and the build must not ship.

use std::collections::HashMap;
use std::path::Path;

use serde::Deserialize;
use serde_json;

use semsql_core::SemsqlError;
use semsql_second_pass::{verify_with_dialect, Invariants, SqlDialect};

#[derive(Deserialize)]
struct Case {
    name: String,
    sql: String,
    scope: HashMap<String, String>,
    should_pass: bool,
}

#[test]
fn two_parsers_agree_across_corpus() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("two_parser_corpus.jsonl");
    assert!(
        path.exists(),
        "fixture missing — run `python -m pytest python/semsql_rewriter/tests/test_two_parser_corpus.py` first"
    );

    let text = std::fs::read_to_string(&path).expect("read fixture");

    let cases: Vec<Case> = text
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| serde_json::from_str(l).expect("parse jsonl entry"))
        .collect();

    assert!(!cases.is_empty(), "corpus empty");

    let mut failures: Vec<String> = Vec::new();
    for case in &cases {
        let mut inv = Invariants::strict();
        for (entity, marker) in &case.scope {
            inv = inv.require_scope(entity, marker);
        }
        let result = verify_with_dialect(&case.sql, &inv, SqlDialect::Sqlite);
        match (case.should_pass, &result) {
            (true, Ok(())) => {}
            (false, Err(SemsqlError::ScopeLeak { .. } | SemsqlError::Validation(_))) => {}
            (true, Err(e)) => failures.push(format!(
                "case {} expected pass, got error: {e}\n  SQL: {}",
                case.name, case.sql
            )),
            (false, Ok(())) => failures.push(format!(
                "case {} expected scope-leak, but verify() accepted it\n  SQL: {}",
                case.name, case.sql
            )),
            (false, Err(e)) => failures.push(format!(
                "case {} expected scope-leak, got unexpected error: {e}\n  SQL: {}",
                case.name, case.sql
            )),
        }
    }

    if !failures.is_empty() {
        panic!(
            "two-parser disagreement: {} of {} cases failed:\n{}",
            failures.len(),
            cases.len(),
            failures.join("\n---\n")
        );
    }
}
